// <auto-generated />
namespace ParadaCerta_API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Registro_Login : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Registro_Login));
        
        string IMigrationMetadata.Id
        {
            get { return "202006131311288_Registro_Login"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
